### PR TITLE
Fix flatten for nested objects with custom depth

### PR DESCRIPTION
**Pull request by KunihikoKido**
The currentDepth was fixed so as to generate from newKey.

### CODE REVIEW

**Comment by sheerun** [comment]
Any example when it currently fails? Maybe a test?

**Comment by KunihikoKido** [comment]
Current test case pattern is successfully. but test case example written in README is failed. Maybe current depth is not reset when move to next top of object.

**Comment by timoxley** [comment]
@KunihikoKido can you add a test that your changes fix to flat's tests?

**Comment by nickpape-msft** [comment]
@timoxley I have a similar solution in #31 , which includes a test.

**Comment by timoxley** [comment]
@KunihikoKido Thanks, this has been fixed in #47

**Pull request closed without merging**
